# Example workflow for PR title validation using the custom action
name: Validate PR Title
on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  validate-title:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Validate PR title
        uses: ./.github/actions/validate_pr_title
        env:
          JIRA_USERNAME: ${{ secrets.JIRA_USERNAME }}
          JIRA_PASSWORD: ${{ secrets.JIRA_PASSWORD }} 
          JIRA_URL: ${{ secrets.JIRA_URL }}
          PATTERN: '^(feat|fix|docs|style|refactor|perf|test|chore)\([A-Z]+-\d+\): .+'
          TITLE: ${{ github.event.pull_request.title }}
